services:
  db:
    image: mariadb:11.8.5
    container_name: inventory-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commerce-inventory
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    ports:
      - "3306:3306"
    volumes:
      - ./inventory_mariadb_data:/var/lib/mysql
