services:
  app:
    image: inventory-service:latest
    container_name: inventory-service
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/commerce-inventory
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    ports:
      - "8083:8083"
    networks:
      - commerce-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8083/actuator/health/liveness"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s

networks:
  commerce-net:
    external: true
