spring:
  application:
    name: inventory-service
  profiles:
    active: local
  web:
    resources:
      add-mappings: false
  jpa:
    open-in-view: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: inventory-service
      auto-offset-reset: earliest
      enable-auto-commit: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

inventory:
  topic:
    default: koosco.commerce.inventory.default
    mappings:
      order:
        cancelled: koosco.commerce.order.cancelled
        confirmed: koosco.commerce.order.confirmed
        placed: koosco.commerce.order.placed
      product:
        "sku.created": koosco.commerce.sku.created
      stock:
        reserved: koosco.commerce.stock.reserved
        "reservation.failed": koosco.commerce.stock.reservation.failed
        confirmed: koosco.commerce.stock.confirmed
        "confirm.failed": koosco.commerce.stock.confirm.failed



springdoc:
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:true}
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    deep-linking: true
  api-docs:
    path: /v3/api-docs
  show-actuator: ${SPRINGDOC_SHOW_ACTUATOR:true}
